### ISSUE TITLE
input for custom server URL

### ISSUE THREAD

**Issue by CeterPushing** [Urabewe/OllamaVision#2]
Hello,

Would it be possible to enhance the OllamaVision UI by incorporating a field that allows users to input a server URL other than `localhost`? For instance, I run my Ollama server on a different machine from the one hosting SwarmUI. Adding this capability to the settings button features would be highly useful.

I was able to modify my instance by updating `OllamaVisionAPI.cs` to point to my Ollama server, and it works flawlessly.

Great extension, by the way!

Cheers!

**Comment by Urabewe** [comment]
Yes all of that is coming and I'm glad you were able to get it connected. If you read the bottom part this was never even meant to go anywhere. So, it is a very basic extension during beta then a lot of the more power user features will be coming later. 

Though this is meant to be a simple local interface I also understand lots of people need remote connections. Soon!

**Comment by Urabewe** [comment]
Remote features will be implemented in future releases.

**Comment by Urabewe** [comment]
Remote Ollama is now implemented
