### ISSUE TITLE
Connect button

### ISSUE THREAD

**Issue by faustoserone** [Urabewe/OllamaVision#3]
**Describe the solution you'd like**
Can you add a "Disconnect from Ollama" button ? (may be useful in case there is an Ollama update to be done)

Great work, BTW

Thanks

**Comment by Urabewe** [comment]
Great idea. I can implement that for the next update.

**Comment by Urabewe** [comment]
Request will be implemented into next release.

**Comment by faustoserone** [comment]
Thank you!

**Comment by Urabewe** [comment]
Disconnect button is now implemented.

**Comment by faustoserone** [comment]
Great! 😀
